#!/bin/bash

for FILE in `find /etc -name "*.dpkg-dist"`; do 
  FILE2=${FILE%.*}
  echo -e "\n\n****************************************************************************\n`ls -l $FILE $FILE2`\n**************************************************************************************************\n\n"
  if [ -f $FILE2 ]; then
    sdiff -s $FILE $FILE2
  fi
done
