#!/bin/bash
if [ -f ../smbmount_all ] && [ -d /mnt ]; then
 echo -e "Start : `date`\n"| tee -a ./mounted.log
 ../smbmount_all --path-look=workgroup/compname --chmod=655 --lowcase --mount_path=/mnt --netbiosname=`hostname` --other-options=codepage=852,iocharset=iso8859-2,fmask=0644 --password=password --user=guest | tee -a ./mounted.log
 echo -e "End : `date`\n\n*****************************************************************************\n"| tee -a ./mounted.log
 else echo "I can't find ../smbmount_all or /mnt doesn't exists!";
fi
